name: Deploy Dev Backend

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
jobs:
  deploy:
    runs-on: [self-hosted, linux, docker]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy backend
        run: |
          echo "Deploying BACKEND DEV"
          cd /srv/backend/dev/backend

          git pull origin dev

          cd ..

          docker compose -f docker.backend.yml up -d --build
