name: Deploy Frontend

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Deploy frontend
        run: |
          if [ "${{ inputs.branch }}" = "dev" ]; then
              echo "Deploying Frontend DEV"
              cd /home/ubuntu/projects/dev/frontend
              git pull
              sudo ./deploy.sh production demo-shipper
          elif [ "${{ inputs.branch }}" = "main" ]; then
              echo "Deploying Frontend PROD"
              cd /home/ubuntu/projects/thecargo/frontend
              git pull
              sudo ./deploy.sh production shipper
          else
              echo "Unknown branch: ${{ inputs.branch }}"
              exit 1
          fi
