name: Deploy Backend

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy backend
        run: |
          if [ "${{ inputs.branch }}" = "dev" ]; then
              echo "Deploying Backend DEV"
              cd /home/ubuntu/projects/dev/frontend
            elif [ "${{ inputs.branch }}" = "main" ]; then
              echo "Deploying Backend PROD"
              cd /home/ubuntu/projects/thecargo/frontend
            else
              echo "Unknown branch: ${{ inputs.branch }}"
              exit 1
            fi
          git pull

          cd ..

          docker compose -f docker.shipper.yml run --remove-orphans --rm react-build
