name: Deploy Backend

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      personal_access_token:
        required: true

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy backend
        run: |
          if [ "${{ inputs.branch }}" = "dev" ]; then
              echo "Deploying Backend DEV"
              sudo /home/ubuntu/projects/dev/frontend/deploy.sh production demo-shipper
            elif [ "${{ inputs.branch }}" = "main" ]; then
              echo "Deploying Backend PROD"
              sudo /home/ubuntu/projects/thecargo/frontend/deploy.sh production shipper
            else
              echo "Unknown branch: ${{ inputs.branch }}"
              exit 1
            fi
