name: Deploy Prod Backend

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, linux, docker]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy backend
        run: |
          echo "Deploying BACKEND PROD"
          cd /srv/backend/prod/backend

          git pull origin main

          cd ..

          docker compose -f docker.backend.yml up -d --build
