name: Deploy Prod Frontend

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, linux, docker]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy frontend
        run: |
          echo "Deploying FRONTEND PROD"
          cd /srv/frontend/prod

          docker compose pull
          docker compose up -d --build
